[package]
name = "nasm-src"
# The version of nasm it builds (2.16.03 upstream).
version = "2.16.3"
edition.workspace = true
description = "The nasm assembler, for the libraries with hand-written assembly"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "nasm"

[build-dependencies]
native-support = { path = "../support" }
