[package]
name = "fribidi-src"
# The version of fribidi it builds.
version = "1.0.16"
edition.workspace = true
description = "A static FriBidi, for libass"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "fribidi"

[build-dependencies]
native-support = { path = "../support" }
