[package]
name = "boost-src"
# The version of boost it builds.
version = "1.87.0"
edition.workspace = true
description = "The Boost headers libtorrent needs"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "boost"

[build-dependencies]
native-support = { path = "../support" }
