[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.28.3"
edition = "2024"
rust-version = "1.94"
license = "AGPL-3.0-or-later"
authors = ["Phrolova <me@phrolova.moe>"]
repository = "https://github.com/phrolova/tinystream"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
