[package]
name = "zimg-src"
# The version of zimg it builds.
version = "3.0.5"
edition.workspace = true
description = "A static zimg, for HDR tonemapping in clips"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "zimg"

[build-dependencies]
native-support = { path = "../support" }
