[package]
name = "freetype-src"
# The version of freetype it builds.
version = "2.13.3"
edition.workspace = true
description = "A static FreeType, for libass"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "freetype"

[build-dependencies]
native-support = { path = "../support" }
