[package]
name = "lame-src"
# The version of LAME it builds.
version = "3.100.0"
edition.workspace = true
description = "A static LAME, for sending music to apps that ask for MP3"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "mp3lame"

[build-dependencies]
native-support = { path = "../support" }
