[package]
name = "harfbuzz-src"
# The version of harfbuzz it builds.
version = "11.2.1"
edition.workspace = true
description = "A static HarfBuzz, for libass"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "harfbuzz"

[dependencies]
freetype-src = { path = "../freetype" }

[build-dependencies]
native-support = { path = "../support" }
