[package]
name = "libass-src"
# The version of libass it builds.
version = "0.17.3"
edition.workspace = true
description = "A static libass, for burning subtitles into clips"
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
links = "ass"

[dependencies]
nasm-src = { path = "../nasm" }
freetype-src = { path = "../freetype" }
fribidi-src = { path = "../fribidi" }
harfbuzz-src = { path = "../harfbuzz" }

[build-dependencies]
native-support = { path = "../support" }
